name: lint and test

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Linter
        run: black --check .

  functional-tests:
    runs-on: ubuntu-latest
    services:
      standalone:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run functional tests
        run: pytest
